ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.message_reactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.message_deletions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.message_stars ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_pins ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_blocks ENABLE ROW LEVEL SECURITY;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.profiles TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.chats TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.chat_participants TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.messages TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.message_reactions TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.message_deletions TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.message_stars TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.chat_pins TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_blocks TO authenticated;
GRANT ALL ON public.profiles TO service_role;
GRANT ALL ON public.chats TO service_role;
GRANT ALL ON public.chat_participants TO service_role;
GRANT ALL ON public.messages TO service_role;
GRANT ALL ON public.message_reactions TO service_role;
GRANT ALL ON public.message_deletions TO service_role;
GRANT ALL ON public.message_stars TO service_role;
GRANT ALL ON public.chat_pins TO service_role;
GRANT ALL ON public.user_blocks TO service_role;
